name: deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  PRODUCTION_URL: https://fullstackopen-pokedex-6s9p.onrender.com/
  COMMIT_CONTAINS_SKIP: ${{ contains(join(github.event.commits.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-modules-${{ runner.os }}-
      - name: cache playwright browsers
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: playwright-browsers-${{ runner.os }}-
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: cache miss; install playwright browsers
        run: npx playwright install --with-deps
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      - name: cache hit; install playwright browsers os deps
        run: npx playwright install-deps
        if: steps.cache-playwright-browsers.outputs.cache-hit == 'true'
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: deploy to Render
        id: deploy-to-render
        if: github.event_name == 'push' && env.COMMIT_CONTAINS_SKIP != 'true'
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        
  tag_release:  
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - if: github.event_name == 'push' && env.COMMIT_CONTAINS_SKIP != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - if: github.event_name == 'push' && env.COMMIT_CONTAINS_SKIP != 'true'
        name: bump version & push tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch

  notify_discord:
    needs: [simple_deployment_pipeline, tag_release]
    runs-on: ubuntu-22.04
    steps:
  #     - name: notify (success)
  #       if: needs.tag_release.result == 'success'
  #       uses: sarisia/actions-status-discord@v1.15.3
  #       with:
  #         webhook: ${{ secrets.DISCORD_BOT_WEBHOOK }}
  #         args: |
  #           ✅ Pokedex deployed!
  #           **by:** ${{ join(github.event.commits.*.committer.username)}}
  #           **view site:** ${{ env.PRODUCTION_URL }}
  #           **commit:** ${{ join(github.event.commits.*.url) }}
      - name: print commit info
        run: echo '${{github.event.head_commit}}'
      