name: deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  PRODUCTION_URL: https://fullstackopen-pokedex-6s9p.onrender.com/
  COMMIT_CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: cache playwright browsers
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: install playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: deploy to Render
        id: deploy-to-render
        if: github.event_name == 'push' && env.COMMIT_CONTAINS_SKIP != 'true'
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
   
        # Discord notification 
      - name: discord notification (succcess)
        if: ${{ steps.deploy-to-render.conclusion.success }}
        run: echo ${{ toJSON(github.event.commit) }}
        # uses: rjstone/discord-webhook-notify@v2
        # with:
        #   webhookUrl: ${{ secrets.DISCORD_BOT_WEBHOOK }}
        #   username: GitHub
        #   avatarUrl: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
        #   severity: info
        #   title: ✅ Pokedex deployed!
        #   description: |
        #     '***commit:*** ${{ toJSON(github.event.commit) }}'
        #     '***view site:*** [${{ env.PRODUCTION_URL }}](${{ env.PRODUCTION_URL }})'
        #   details: not needed because we overrode default description.
        #   footer: This embed was brought to you by the letter R and the number 4.


  tag_release:  
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - if: github.event_name == 'push' && env.COMMIT_CONTAINS_SKIP != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - if: github.event_name == 'push' && env.COMMIT_CONTAINS_SKIP != 'true'
        name: bump version & push tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
